/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as Page1IndexRouteImport } from './routes/page-1/index'
import { Route as Page2IndexRouteImport } from './routes/page-2/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const Page1IndexRoute = Page1IndexRouteImport.update({
  id: '/page-1/',
  path: '/page-1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Page2IndexRoute = Page2IndexRouteImport.update({
  id: '/page-2/',
  path: '/page-2/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/page-1/': typeof Page1IndexRoute
  '/page-2/': typeof Page2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404IndexRoute
  '/page-1': typeof Page1IndexRoute
  '/page-2': typeof Page2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/page-1/': typeof Page1IndexRoute
  '/page-2/': typeof Page2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/404/' | '/page-1/' | '/page-2/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/404' | '/page-1' | '/page-2'
  id: '__root__' | '/' | '/404/' | '/page-1/' | '/page-2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404IndexRoute: typeof R404IndexRoute
  Page1IndexRoute: typeof Page1IndexRoute
  Page2IndexRoute: typeof Page2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404/'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-1/': {
      id: '/page-1/'
      path: '/page-1'
      fullPath: '/page-1/'
      preLoaderRoute: typeof Page1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page-2/': {
      id: '/page-2/'
      path: '/page-2'
      fullPath: '/page-2/'
      preLoaderRoute: typeof Page2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404IndexRoute: R404IndexRoute,
  Page1IndexRoute: Page1IndexRoute,
  Page2IndexRoute: Page2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
